name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run linters
        run: make lint

      - name: Run tests
        run: poetry run pytest --cov=hexlet_code --cov-report=xml

      - name: Upload coverage to Code Climate
        run: |
          coverage report
          coverage xml
          bash <(curl -s https://codeclimate.com/test_reports) -t ${{ secrets.CC_TEST_REPORTER_ID }} -r

